[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.2.0"
edition = "2021"
readme = "README.md"

[dependencies]
crc32fast = "1.0.0"
md-5 = "0.10.5"
sha1 = "0.10.5"
sha2 = "0.10.6"
blake2 = "0.10.5"
digest = "0.10.6"
hex = "0.4.3"
log = "0.4.17"
env_logger = "0.10.0"
walkdir = "2.3.2"
serde = "1.0.152"
serde_derive = "1.0.152"
config-file = "0.2.3"

[dependencies.clap]
version = "4.1.4"
features = ["derive"]
