[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.4.4"
edition = "2021"
readme = "README.md"

[dependencies]
crc32fast = "1.0.0"
md2 = "0.10.2"
md4 = "0.10.2"
md-5 = "0.10.5"
sha1 = "0.10.5"
sha2 = "0.10.6"
sha3 = "0.10.6"
blake2 = "0.10.5"
belt-hash = "0.1.0"
whirlpool = "0.10.4"
tiger = "0.2.1"
streebog = "0.10.2"
ripemd = "0.1.3"
fsb = "0.1.3"
sm3 = "0.4.1"
gost94 = "0.10.4"
groestl = "0.10.1"
shabal = "0.4.1"
digest = "0.10.6"
hex = "0.4.3"
log = "0.4.17"
env_logger = "0.10.0"
walkdir = "2.3.2"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
chrono = "0.4.23"
toml = "0.7.1"
clap-verbosity-flag = "2.0.0"

[dependencies.clap]
version = "4.1.4"
features = ["derive"]

[dependencies.tokio]
version = "1.25.0"
features = ["rt", "macros"]

[dependencies.sqlx]
version = "0.6.2"
features = ["postgres", "mysql", "sqlite", "any", "runtime-tokio-native-tls"]
