[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.1.0"
edition = "2021"
author = "Meemo <meemo4556@gmail.com>"
readme = "README.md"

[dependencies]
md-5 = "0.10.5"
sha1 = "0.10.5"
sha2 = "0.10.6"
blake2 = "0.10.5"
digest = "0.10.6"
data-encoding = "2.3.3"
