[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.0.1"
edition = "2021"
author = "Meemo <meemo4556@gmail.com>"
readme = "README.md"

[dependencies]
sha2 = "0.10.6"
data-encoding = "2.3.3"
