[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.1.1"
edition = "2021"
readme = "README.md"

[dependencies]
crc32fast = "1.0.0"
md-5 = "0.10.5"
sha1 = "0.10.5"
sha2 = "0.10.6"
blake2 = "0.10.5"
digest = "0.10.6"
hex = "0.4.3"
