[package]
name = "hasher"
description = "A parallel file hashing program."
version = "0.0.1"
edition = "2021"
author = "Meemo <meemo4556@gmail.com>"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
