[database]
# `myhashes.db` can be changed if you wish.
db_string = "sqlite://myhashes.db"
table_name = "hashes"

[hashes]
crc32 = true
md2 = false
md4 = false
md5 = true
sha1 = true
sha224 = false
sha256 = true
sha384 = false
sha512 = false
sha3_224 = false
sha3_256 = false
sha3_384 = false
sha3_512 = false
keccak224 = false
keccak256 = false
keccak384 = false
keccak512 = false
blake2s256 = false
blake2b512 = false
belt_hash = false
whirlpool = false
tiger = false
tiger2 = false
streebog256 = false
streebog512 = false
ripemd128 = false
ripemd160 = false
ripemd256 = false
ripemd320 = false
fsb160 = false
fsb224 = false
fsb256 = false
fsb384 = false
fsb512 = false
sm3 = false
gost94_cryptopro = false
gost94_test = false
gost94_ua = false
gost94_s2015 = false
groestl224 = false
groestl256 = false
groestl384 = false
groestl512 = false
shabal192 = false
shabal224 = false
shabal256 = false
shabal384 = false
shabal512 = false
